## Koşullu Eleman İşlemleri

In [2]:
import numpy as np

In [3]:
v = np.array([1,2,3,4,5])

In [4]:
v>5

array([False, False, False, False, False])

In [5]:
v>3

array([False, False, False,  True,  True])

In [6]:
v[v<3]

array([1, 2])

In [7]:
v

array([1, 2, 3, 4, 5])

In [8]:
v*2

array([ 2,  4,  6,  8, 10])

In [9]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)