# NumPy Array Oluşturmak

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [6]:
#sifirdan array olusturma

In [8]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [11]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.random.normal(10,4,(3,4)) #ortalaması 10, std.sapması 4, 3x4 matris

array([[14.46507612,  5.68214633, -1.36059412, 13.84682217],
       [13.1017568 , 13.12990184, 12.50157028,  6.36046835],
       [13.81998231,  9.98866271, 13.69886968,  9.25889968]])

In [15]:
np.random.randint(0,10, (3,3))

array([[2, 4, 2],
       [8, 0, 1],
       [6, 3, 9]])