## Matematiksel İşlemler

In [1]:
import numpy as np
v = np.array([1,2,3,4,5])

In [2]:
v-1

array([0, 1, 2, 3, 4])

In [3]:
v*5

array([ 5, 10, 15, 20, 25])

In [4]:
#ufunc

In [5]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [6]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [7]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [8]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [10]:
np.absolute(np.array([-3,8,11,-2,0]))

array([ 3,  8, 11,  2,  0])

In [13]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])