## Alt Küme Üzerinde İşlem Yapmak

In [4]:
import numpy as np

In [6]:
a = np.random.randint(10,size=(5,5))
a

array([[7, 6, 3, 9, 3],
       [0, 2, 5, 8, 8],
       [0, 7, 6, 6, 4],
       [2, 0, 5, 4, 3],
       [8, 8, 6, 0, 4]])

In [8]:
alt_a = a[:3,:2]
alt_a

array([[7, 6],
       [0, 2],
       [0, 7]])

In [13]:
alt_a[0,0]=9999 #ana arrayi de etkiliyor.
alt_a[1,1]=888

In [10]:
alt_a

array([[9999,    6],
       [   0,  888],
       [   0,    7]])

In [11]:
a

array([[9999,    6,    3,    9,    3],
       [   0,  888,    5,    8,    8],
       [   0,    7,    6,    6,    4],
       [   2,    0,    5,    4,    3],
       [   8,    8,    6,    0,    4]])

In [14]:
m = np.random.randint(10,size=(5,5))
m

array([[0, 1, 7, 0, 4],
       [4, 6, 3, 4, 4],
       [3, 0, 1, 9, 0],
       [8, 9, 7, 1, 6],
       [0, 1, 5, 3, 8]])

In [15]:
alt_b = m[:3,:2].copy() #copy() methodu ile alt kume bagımsız hale gelir.

In [16]:
alt_b

array([[0, 1],
       [4, 6],
       [3, 0]])

In [19]:
alt_b[0,0] = 1000 #ana array'i etkilemez
alt_b

array([[1000,    1],
       [   4,    6],
       [   3,    0]])

In [18]:
m

array([[0, 1, 7, 0, 4],
       [4, 6, 3, 4, 4],
       [3, 0, 1, 9, 0],
       [8, 9, 7, 1, 6],
       [0, 1, 5, 3, 8]])