## Array Sıralama(Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [5]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [6]:
v

array([2, 1, 4, 3, 5])

In [7]:
v.sort()

In [8]:
v

array([1, 2, 3, 4, 5])

In [9]:
#iki boyutlu array siralama

In [10]:
m = np.random.normal(20,5, (3,3))
m

array([[11.42152752, 21.18607123, 15.81460334],
       [15.69155585, 12.78225233, 16.04862665],
       [13.80658088, 18.52825663, 27.67721721]])

In [13]:
np.sort(m,axis = 1)

array([[11.42152752, 15.81460334, 21.18607123],
       [12.78225233, 15.69155585, 16.04862665],
       [13.80658088, 18.52825663, 27.67721721]])

In [14]:
np.sort(m,axis=0)

array([[11.42152752, 12.78225233, 15.81460334],
       [13.80658088, 18.52825663, 16.04862665],
       [15.69155585, 21.18607123, 27.67721721]])