## Array Alt Kümesine Erişmek(Slicing)

In [6]:
import numpy as np

In [8]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
a[0:3]

array([20, 21, 22])

In [10]:
a[:3]

array([20, 21, 22])

In [11]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [12]:
a[1::2]

array([21, 23, 25, 27, 29])

In [13]:
a[0::2]

array([20, 22, 24, 26, 28])

In [14]:
#iki boyutlu slice işlemleri

In [16]:
m = np.random.randint(10,size=(5,5))
m

array([[4, 7, 6, 3, 7],
       [7, 0, 6, 4, 6],
       [5, 3, 2, 3, 8],
       [3, 9, 5, 3, 2],
       [6, 4, 2, 9, 5]])

In [17]:
m[:,0]

array([4, 7, 5, 3, 6])

In [18]:
m[0,:]

array([4, 7, 6, 3, 7])

In [19]:
m[0:2,0:3]

array([[4, 7, 6],
       [7, 0, 6]])

In [20]:
m[:,:2]

array([[4, 7],
       [7, 0],
       [5, 3],
       [3, 9],
       [6, 4]])

In [21]:
m[1:3,:2]

array([[7, 0],
       [5, 3]])