## Index ile Elemanlara Erişmek

In [1]:
import numpy as np
a = np.random.randint(10,size=10)
a

array([9, 8, 7, 2, 6, 9, 8, 8, 6, 1])

In [2]:
a[0]

9

In [3]:
a[-1]

1

In [4]:
a[0] = 100

In [5]:
a

array([100,   8,   7,   2,   6,   9,   8,   8,   6,   1])

In [6]:
m = np.random.randint(10,size= (3,5))
m

array([[4, 5, 7, 7, 1],
       [7, 7, 8, 5, 9],
       [7, 3, 7, 0, 0]])

In [7]:
m[0,0]

4

In [8]:
m[1,1]

7

In [10]:
m[1,4]

9

In [11]:
m[1,4] = 99

In [12]:
m

array([[ 4,  5,  7,  7,  1],
       [ 7,  7,  8,  5, 99],
       [ 7,  3,  7,  0,  0]])

In [15]:
m[1,4] = 2.2 #array elemanları int olduğu için 2 olarak atanır.

In [14]:
m

array([[4, 5, 7, 7, 1],
       [7, 7, 8, 5, 2],
       [7, 3, 7, 0, 0]])